server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
         # uri: http://localhost:8001          #匹配后提供服务的路由地址  lb代表负载均衡LoadBalanced
          uri: lb://pay-com.atwangjin.cloud.service          #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**         # 断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
        #  uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://pay-com.atwangjin.cloud.service          #开启负载均衡
          predicates:
            - Path=/payment/lb/**         # 断言，路径相匹配的进行路由
            - After=2022-05-01T21:08:24.062+08:00[Asia/Shanghai]
            #要在此时间之后lb请求访问才会有效
            #     - Before=2022-05-01T21:08:24.062+08:00[Asia/Shanghai]
            #     - Between=2022-05-01T21:08:24.062+08:00[Asia/Shanghai] ,  2022-05-01T21:08:24.062+08:00[Asia/Shanghai]
            #      - Cookie=username,zzyy   #Cookie=cookieName,正则表达式
            # 请求头要有X-Request-Id属性并且值为整数的正则表达式 curl http://localhost:9527/payment/lb --cookie "username=zzyy" -H "X-Request-Id:11"
            # - Header=X-Request-Id, \d+
            #  - Host=**.atguigu.com  # curl http://localhost:9527/payment/lb -H "Host:afae.atguigu.com"




eureka:
  instance:
    hostname: gateway-com.atwangjin.cloud.service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
