server:
  port: 8006

spring:
  application:
    name: pay-com.atwangjin.cloud.com.atwangjin.cloud.service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        #hostname:127.0.0.1
        service-name: ${spring.application.name}

