server:
  port: 8002

spring:
  application:
    name: pay-com.atwangjin.cloud.service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource

    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/could?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atwangjin.could.pojo

eureka:
  client:
    register-with-eureka: true #是否向注册中心注册自己
    fetchRegistry: true #是否从注册中心抓取已有的注册信息 默认true，集群必须设置为true
    service-url:
      #      设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      #             http://localhost:7001/eureka  单机版
      defaultZone:  http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/  #集群版


  instance:
    instance-id: payment8002  #修改服务主机名
    prefer-ip-address: true  #显示ip




