server:
  port: 9003

spring:
  application:
    name: nacos-payment-provider

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  #此处找的是liunx上的nginx端口然后由nginx分配nacos集群服务器


management:
  endpoints:
    web:
      exposure:
        include: '*'
