server:
  port: 80



eureka:
  client:
    register-with-eureka: false #是否向注册中心注册自己
    service-url:
      #      设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone:  http://localhost:7001/eureka  #单机版
      # defaultZone:  http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/  #集群版

#关闭会报错timeout,因为此处模拟了一个3秒的复杂业务逻辑程序,超过ribbon默认等待时间
#ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下, 两端连接所用的时间
  #ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  #ConnectTimeout: 5000

feign:
  hystrix:
    enabled: true